### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by dragonexpert** [mrnu/staff-page#1]
Using strtolower is not necessary when using ==.  It would only be necessary if you are using === which forces exact matches including type.  

Instead of using $_SERVER['PHP_SELF'] you should use the constant THIS_SCRIPT.  All core files that constant will be like filename.php. This will make your code more consistent with MyBB coding standards.  Similarly, use either $mybb->input['parameter'] or $mybb->get_input($parameter) instead of the superglobal $_GET.

This part is a bit confusing:
$query = $db->simple_select('staff_page_members', '*', $group_id ? ('group_id = ' . intval($group_id)) : '1', array('order_by'  =>  'user_id', 'order_dir'  =>  'ASC'));
Overall I really dislike using ternary operators even if it is shorter.  It is much harder to read.

**Comment by ghost** [comment]
Thank you for your feedback. Code improved.

mrnu/staff-page@43e178745dae652b8f5171120c146f9b05656ead
